export const anatomyPointsData = [
  {
    location: "Proximal Arm",
    abbreviation: "PA",
    side: "Left",
    x: 105,
    y: 150,
  },
  {
    location: "Proximal Arm",
    abbreviation: "PA",
    side: "Right",
    x: 235,
    y: 150,
  },
  {
    location: "Distal Arm",
    abbreviation: "DA",
    side: "Left",
    x: 60,
    y: 210,
  },
  {
    location: "Distal Arm",
    abbreviation: "DA",
    side: "Right",
    x: 275,
    y: 210,
  },
  {
    location: "Proximal Thigh",
    abbreviation: "PT",
    side: "Left",
    x: 140,
    y: 310,
  },
  {
    location: "Proximal Thigh",
    abbreviation: "PT",
    side: "Right",
    x: 210,
    y: 310,
  },
  {
    location: "Distal Thigh",
    abbreviation: "DT",
    side: "Left",
    x: 145,
    y: 355,
  },
  {
    location: "Distal Thigh",
    abbreviation: "DT",
    side: "Right",
    x: 200,
    y: 355,
  },
  { location: "Calf", abbreviation: "C", side: "Left", x: 145, y: 410 },
  { location: "Calf", abbreviation: "C", side: "Right", x: 200, y: 410 },
  { location: "Ankle", abbreviation: "A", side: "Left", x: 150, y: 455 },
  { location: "Ankle", abbreviation: "A", side: "Right", x: 200, y: 455 },
  { location: "Foot", abbreviation: "F", side: "Left", x: 150, y: 520 },
  { location: "Foot", abbreviation: "F", side: "Right", x: 190, y: 520 },
];
