export const billingData = [
  {
    id: 1,
    report_no: "REP10001",
    ordering_provider: "Health Diagnostics Inc.",
    ordering_physician: "Dr. Smith",
    bill_date: "2025-02-15",
    bill_amount: 250.0,
    patient: {
      id: 101,
      first_name: "John",
      last_name: "Doe",
      email: "john.doe@example.com",
      phone: "(555) 123-4567",
      address: "123 Main St",
      apt_number: "10234",
      gender: "Male",
      date_of_birth: "1980-05-15",
      insurance_company: "Blue Cross",
      member_id: "BC123456789",
      reasons: ["Headache", "Dizziness"],
      sensory_symptoms: ["Numbness in hands"],
      ethnicity: "Caucasian",
    },
  },
  {
    id: 2,
    report_no: "REP10002",
    ordering_provider: "MediCare Labs",
    ordering_physician: "Dr. Lee",
    bill_date: "2025-02-16",
    bill_amount: 300.0,
    patient: {
      id: 102,
      first_name: "Emily",
      last_name: "Johnson",
      email: "emily.johnson@example.com",
      phone: "(555) 987-6543",
      address: "456 Oak Rd",
      apt_number: "45321",
      gender: "Female",
      date_of_birth: "1992-09-24",
      insurance_company: "Aetna",
      member_id: "AT987654321",
      reasons: ["Chest pain", "Shortness of breath"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "Hispanic",
    },
  },
  {
    id: 3,
    report_no: "REP10003",
    ordering_provider: "Prime Diagnostics",
    ordering_physician: "Dr. White",
    bill_date: "2025-02-17",
    bill_amount: 180.0,
    patient: {
      id: 103,
      first_name: "Michael",
      last_name: "Brown",
      email: "michael.brown@example.com",
      phone: "(555) 345-6789",
      address: "789 Pine Ln",
      apt_number: "98765",
      gender: "Male",
      date_of_birth: "1975-02-10",
      insurance_company: "United Healthcare",
      member_id: "UH112233445",
      reasons: ["Abdominal pain", "Nausea"],
      sensory_symptoms: ["Dizziness"],
      ethnicity: "African American",
    },
  },
  {
    id: 4,
    report_no: "REP10004",
    ordering_provider: "Health First Labs",
    ordering_physician: "Dr. Green",
    bill_date: "2025-02-18",
    bill_amount: 220.0,
    patient: {
      id: 104,
      first_name: "Sarah",
      last_name: "Miller",
      email: "sarah.miller@example.com",
      phone: "(555) 678-1234",
      address: "321 Birch Blvd",
      apt_number: "54321",
      gender: "Female",
      date_of_birth: "1988-11-18",
      insurance_company: "Cigna",
      member_id: "CG998877665",
      reasons: ["Joint pain", "Swelling"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "Asian",
    },
  },
  {
    id: 5,
    report_no: "REP10005",
    ordering_provider: "MedLine Diagnostics",
    ordering_physician: "Dr. Black",
    bill_date: "2025-02-19",
    bill_amount: 275.0,
    patient: {
      id: 105,
      first_name: "David",
      last_name: "Martinez",
      email: "david.martinez@example.com",
      phone: "(555) 456-7890",
      address: "654 Maple Dr",
      apt_number: "98476",
      gender: "Male",
      date_of_birth: "1990-07-30",
      insurance_company: "Aetna",
      member_id: "AT665544332",
      reasons: ["Back pain", "Sciatica"],
      sensory_symptoms: ["Leg numbness"],
      ethnicity: "Hispanic",
    },
  },
  {
    id: 6,
    report_no: "REP10006",
    ordering_provider: "MedStar Labs",
    ordering_physician: "Dr. Wilson",
    bill_date: "2025-02-20",
    bill_amount: 320.0,
    patient: {
      id: 106,
      first_name: "Olivia",
      last_name: "Davis",
      email: "olivia.davis@example.com",
      phone: "(555) 234-5678",
      address: "890 Cedar St",
      apt_number: "67945",
      gender: "Female",
      date_of_birth: "1995-03-21",
      insurance_company: "Humana",
      member_id: "HU445566778",
      reasons: ["Leg pain", "Cramps"],
      sensory_symptoms: ["Tingling in feet"],
      ethnicity: "Caucasian",
    },
  },
  {
    id: 7,
    report_no: "REP10007",
    ordering_provider: "Advanced MedTech",
    ordering_physician: "Dr. Adams",
    bill_date: "2025-02-21",
    bill_amount: 150.0,
    patient: {
      id: 107,
      first_name: "James",
      last_name: "Wilson",
      email: "james.wilson@example.com",
      phone: "(555) 567-8901",
      address: "234 Elm Ave",
      apt_number: "56789",
      gender: "Male",
      date_of_birth: "1983-12-12",
      insurance_company: "Blue Shield",
      member_id: "BS223344556",
      reasons: ["Chest pain", "Fatigue"],
      sensory_symptoms: ["None"],
      ethnicity: "African American",
    },
  },
  {
    id: 8,
    report_no: "REP10008",
    ordering_provider: "MediScan",
    ordering_physician: "Dr. Mitchell",
    bill_date: "2025-02-22",
    bill_amount: 280.0,
    patient: {
      id: 108,
      first_name: "Isabella",
      last_name: "Thomas",
      email: "isabella.thomas@example.com",
      phone: "(555) 678-9876",
      address: "135 Willow Dr",
      apt_number: "87654",
      gender: "Female",
      date_of_birth: "1998-08-22",
      insurance_company: "Cigna",
      member_id: "CG778899001",
      reasons: ["Abdominal discomfort", "Bloating"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "White",
    },
  },
  {
    id: 9,
    report_no: "REP10009",
    ordering_provider: "ProHealth Diagnostics",
    ordering_physician: "Dr. Robinson",
    bill_date: "2025-02-23",
    bill_amount: 310.0,
    patient: {
      id: 109,
      first_name: "Matthew",
      last_name: "Anderson",
      email: "matthew.anderson@example.com",
      phone: "(555) 890-1234",
      address: "567 Oak Ln",
      apt_number: "76543",
      gender: "Male",
      date_of_birth: "1993-04-05",
      insurance_company: "United Healthcare",
      member_id: "UH443322110",
      reasons: ["Back pain", "Muscle strain"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "Caucasian",
    },
  },
  {
    id: 10,
    report_no: "REP10010",
    ordering_provider: "Wellness Labs",
    ordering_physician: "Dr. Clark",
    bill_date: "2025-02-24",
    bill_amount: 260.0,
    patient: {
      id: 110,
      first_name: "Sophia",
      last_name: "Harris",
      email: "sophia.harris@example.com",
      phone: "(555) 111-2233",
      address: "901 Spruce St",
      apt_number: "43210",
      gender: "Female",
      date_of_birth: "1987-06-17",
      insurance_company: "Aetna",
      member_id: "AT998877665",
      reasons: ["Frequent headaches"],
      sensory_symptoms: ["Blurred vision"],
      ethnicity: "Hispanic",
    },
  },
  {
    id: 11,
    report_no: "REP10011",
    ordering_provider: "Precision Diagnostics",
    ordering_physician: "Dr. Foster",
    bill_date: "2025-02-25",
    bill_amount: 275.0,
    patient: {
      id: 111,
      first_name: "Daniel",
      last_name: "Lopez",
      email: "daniel.lopez@example.com",
      phone: "(555) 222-3344",
      address: "678 Birch St",
      apt_number: "23109",
      gender: "Male",
      date_of_birth: "1980-10-29",
      insurance_company: "Humana",
      member_id: "HU123456789",
      reasons: ["Chest tightness", "Cough"],
      sensory_symptoms: ["None"],
      ethnicity: "Latino",
    },
  },
  {
    id: 12,
    report_no: "REP10012",
    ordering_provider: "MedTrust Labs",
    ordering_physician: "Dr. Simmons",
    bill_date: "2025-02-26",
    bill_amount: 200.0,
    patient: {
      id: 112,
      first_name: "Ava",
      last_name: "Walker",
      email: "ava.walker@example.com",
      phone: "(555) 333-4455",
      address: "123 Redwood Ave",
      apt_number: "11098",
      gender: "Female",
      date_of_birth: "1996-12-05",
      insurance_company: "Blue Shield",
      member_id: "BS554433221",
      reasons: ["Dizziness", "Nausea"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "Asian",
    },
  },
  {
    id: 13,
    report_no: "REP10013",
    ordering_provider: "RapidTest Diagnostics",
    ordering_physician: "Dr. Evans",
    bill_date: "2025-02-27",
    bill_amount: 190.0,
    patient: {
      id: 113,
      first_name: "Ethan",
      last_name: "Hall",
      email: "ethan.hall@example.com",
      phone: "(555) 444-5566",
      address: "234 Oakwood Dr",
      apt_number: "88765",
      gender: "Male",
      date_of_birth: "1978-09-11",
      insurance_company: "United Healthcare",
      member_id: "UH667788990",
      reasons: ["Neck pain"],
      sensory_symptoms: ["Tingling in arms"],
      ethnicity: "White",
    },
  },
  {
    id: 14,
    report_no: "REP10014",
    ordering_provider: "Precision Care",
    ordering_physician: "Dr. Morgan",
    bill_date: "2025-02-28",
    bill_amount: 350.0,
    patient: {
      id: 114,
      first_name: "Mia",
      last_name: "King",
      email: "mia.king@example.com",
      phone: "(555) 555-6677",
      address: "876 Poplar St",
      apt_number: "87632",
      gender: "Female",
      date_of_birth: "1991-04-08",
      insurance_company: "Cigna",
      member_id: "CG889900112",
      reasons: ["Joint swelling"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "African American",
    },
  },
  {
    id: 15,
    report_no: "REP10015",
    ordering_provider: "CarePoint Labs",
    ordering_physician: "Dr. Bell",
    bill_date: "2025-03-01",
    bill_amount: 225.0,
    patient: {
      id: 115,
      first_name: "Lucas",
      last_name: "Wright",
      email: "lucas.wright@example.com",
      phone: "(555) 666-7788",
      address: "345 Magnolia Blvd",
      apt_number: "65498",
      gender: "Male",
      date_of_birth: "1985-05-21",
      insurance_company: "Blue Cross",
      member_id: "BC223344556",
      reasons: ["Fatigue", "Weakness"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "Hispanic",
    },
  },
  {
    id: 16,
    report_no: "REP10016",
    ordering_provider: "BioHealth Labs",
    ordering_physician: "Dr. Rogers",
    bill_date: "2025-03-02",
    bill_amount: 285.0,
    patient: {
      id: 116,
      first_name: "Charlotte",
      last_name: "Scott",
      email: "charlotte.scott@example.com",
      phone: "(555) 777-8899",
      address: "567 Cypress Ln",
      apt_number: "32567",
      gender: "Female",
      date_of_birth: "1989-07-14",
      insurance_company: "Humana",
      member_id: "HU998877665",
      reasons: ["Frequent infections"],
      sensory_symptoms: ["None"],
      ethnicity: "Asian",
    },
  },
  {
    id: 17,
    report_no: "REP10017",
    ordering_provider: "LifeCheck Diagnostics",
    ordering_physician: "Dr. Stewart",
    bill_date: "2025-03-03",
    bill_amount: 195.0,
    patient: {
      id: 117,
      first_name: "Mason",
      last_name: "Young",
      email: "mason.young@example.com",
      phone: "(555) 888-9900",
      address: "890 Aspen Way",
      apt_number: "78965",
      gender: "Male",
      date_of_birth: "1994-10-01",
      insurance_company: "Aetna",
      member_id: "AT554433221",
      reasons: ["Breathing issues"],
      sensory_symptoms: ["None"],
      ethnicity: "African American",
    },
  },
  {
    id: 18,
    report_no: "REP10018",
    ordering_provider: "MediCheck Labs",
    ordering_physician: "Dr. Hughes",
    bill_date: "2025-03-04",
    bill_amount: 210.0,
    patient: {
      id: 118,
      first_name: "Amelia",
      last_name: "Rodriguez",
      email: "amelia.rodriguez@example.com",
      phone: "(555) 999-0011",
      address: "123 Sycamore St",
      apt_number: "11234",
      gender: "Female",
      date_of_birth: "1982-02-27",
      insurance_company: "Cigna",
      member_id: "CG334455667",
      reasons: ["Digestive issues"],
      sensory_symptoms: ["Bloating"],
      ethnicity: "Hispanic",
    },
  },
];
