const painTypes = [
  {
    id: 1,
    title: "Leg Pain",
    isHidden: false,
    disorders: [
      {
        id: 101,
        type: "E03.9 Hypothyroidism, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 102,
        type: "E07.9 Disorder of thyroid, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 103,
        type: "E10.40 Type 1 DM with diabetic neuropathy, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 104,
        type: "E11.40 Type 2 DM with diabetic neuropathy, unspecified",
        isHidden: false,
        sides: [],
      },
      { id: 105, type: "E16.2 Hypoglycemia", isHidden: false, sides: [] },
      {
        id: 106,
        type: "E53.8 Deficiency of B group vitamins",
        isHidden: false,
        sides: [],
      },
      { id: 107, type: "M79.2 Fibromyalgia", isHidden: false, sides: [] },
      { id: 108, type: "M54.5 Low back pain", isHidden: false, sides: [] },
      {
        id: 109,
        type: "M47.9 Spondylosis, unspecified",
        isHidden: true,
        sides: [],
      },
      {
        id: 110,
        type: "M25.5 Pain in joint, unspecified",
        isHidden: true,
        sides: [],
      },
    ],
  },
  {
    id: 2,
    title: "Chest Pain",
    isHidden: false,
    disorders: [
      {
        id: 201,
        type: "I20.9 Angina pectoris, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 202,
        type: "I21.9 Acute myocardial infarction, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 203,
        type: "I22.9 Subsequent myocardial infarction, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 204,
        type: "R07.9 Chest pain, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 205,
        type: "J44.9 Chronic obstructive pulmonary disease",
        isHidden: false,
        sides: [],
      },
      {
        id: 206,
        type: "R06.02 Shortness of breath",
        isHidden: false,
        sides: [],
      },
      {
        id: 207,
        type: "K21.9 Gastro-esophageal reflux disease",
        isHidden: false,
        sides: [],
      },
      { id: 208, type: "R55 Syncope and collapse", isHidden: false, sides: [] },
      {
        id: 209,
        type: "I11.9 Hypertensive heart disease",
        isHidden: true,
        sides: [],
      },
      { id: 210, type: "I63.9 Cerebral infarction", isHidden: true, sides: [] },
    ],
  },
  {
    id: 3,
    title: "Headache",
    isHidden: false,
    disorders: [
      {
        id: 301,
        type: "G43.9 Migraine, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 302,
        type: "G44.1 Tension-type headache",
        isHidden: false,
        sides: [],
      },
      { id: 303, type: "R51 Headache", isHidden: false, sides: [] },
      { id: 304, type: "G44.2 Cluster headache", isHidden: false, sides: [] },
      {
        id: 305,
        type: "G45.9 Transient cerebral ischemic attack",
        isHidden: false,
        sides: [],
      },
      {
        id: 306,
        type: "I63.9 Cerebral infarction",
        isHidden: false,
        sides: [],
      },
      {
        id: 307,
        type: "R42 Dizziness and giddiness",
        isHidden: false,
        sides: [],
      },
      {
        id: 308,
        type: "G45.0 Vertebrobasilar artery syndrome",
        isHidden: false,
        sides: [],
      },
      {
        id: 309,
        type: "G44.3 Post-traumatic headache",
        isHidden: true,
        sides: [],
      },
      {
        id: 310,
        type: "G44.4 Chronic tension-type headache",
        isHidden: true,
        sides: [],
      },
    ],
  },
  {
    id: 4,
    title: "Abdominal Pain",
    isHidden: false,
    disorders: [
      {
        id: 401,
        type: "R10.9 Abdominal pain, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 402,
        type: "K21.9 Gastro-esophageal reflux disease",
        isHidden: false,
        sides: [],
      },
      { id: 403, type: "K25.9 Gastric ulcer", isHidden: false, sides: [] },
      {
        id: 404,
        type: "K70.9 Alcoholic liver disease",
        isHidden: false,
        sides: [],
      },
      {
        id: 405,
        type: "K52.9 Noninfective gastroenteritis",
        isHidden: false,
        sides: [],
      },
      {
        id: 406,
        type: "I10 Essential hypertension",
        isHidden: false,
        sides: [],
      },
      { id: 407, type: "K80.9 Cholelithiasis", isHidden: false, sides: [] },
      { id: 408, type: "K30 Dyspepsia", isHidden: false, sides: [] },
      { id: 409, type: "K41.9 Inguinal hernia", isHidden: true, sides: [] },
      {
        id: 410,
        type: "R63.5 Abnormal weight gain",
        isHidden: true,
        sides: [],
      },
    ],
  },
  {
    id: 5,
    title: "Joint Pain",
    isHidden: false,
    disorders: [
      {
        id: 501,
        type: "M15.9 Osteoarthritis, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 502,
        type: "M17.9 Osteoarthritis of knee",
        isHidden: false,
        sides: [],
      },
      { id: 503, type: "M19.9 Osteoarthritis", isHidden: false, sides: [] },
      {
        id: 504,
        type: "M30.9 Systemic vasculitis",
        isHidden: false,
        sides: [],
      },
      {
        id: 505,
        type: "M45.9 Ankylosing spondylitis",
        isHidden: false,
        sides: [],
      },
      { id: 506, type: "M79.7 Fibromyalgia", isHidden: false, sides: [] },
      { id: 507, type: "M54.5 Low back pain", isHidden: false, sides: [] },
      { id: 508, type: "M77.9 Tendinitis", isHidden: false, sides: [] },
      { id: 509, type: "M76.9 Plantar fasciitis", isHidden: true, sides: [] },
      {
        id: 510,
        type: "M19.0 Primary osteoarthritis of hip",
        isHidden: true,
        sides: [],
      },
    ],
  },
  {
    id: 6,
    title: "Neck Pain",
    isHidden: false,
    disorders: [
      { id: 601, type: "M54.2 Cervicalgia", isHidden: false, sides: [] },
      { id: 602, type: "M54.3 Sciatica", isHidden: false, sides: [] },
      {
        id: 603,
        type: "M51.9 Intervertebral disc disorder, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 604,
        type: "M54.4 Lumbago with sciatica",
        isHidden: false,
        sides: [],
      },
      {
        id: 605,
        type: "M62.9 Muscle disorder, unspecified",
        isHidden: false,
        sides: [],
      },
      { id: 606, type: "M53.8 Other dorsopathies", isHidden: false, sides: [] },
      {
        id: 607,
        type: "M76.8 Other enthesopathies of lower limb",
        isHidden: false,
        sides: [],
      },
      {
        id: 608,
        type: "M99.01 Segmental and somatic dysfunction of cervical region",
        isHidden: false,
        sides: [],
      },
      {
        id: 609,
        type: "M41.9 Scoliosis, unspecified",
        isHidden: true,
        sides: [],
      },
      {
        id: 610,
        type: "M60.9 Myositis, unspecified",
        isHidden: true,
        sides: [],
      },
    ],
  },
  {
    id: 7,
    title: "Back Pain",
    isHidden: false,
    disorders: [
      { id: 701, type: "M54.5 Low back pain", isHidden: false, sides: [] },
      {
        id: 702,
        type: "M51.9 Intervertebral disc disorder, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 703,
        type: "M53.2 Spinal stenosis, cervical region",
        isHidden: false,
        sides: [],
      },
      {
        id: 704,
        type: "M54.4 Lumbago with sciatica",
        isHidden: false,
        sides: [],
      },
      { id: 705, type: "M79.1 Myalgia", isHidden: false, sides: [] },
      {
        id: 706,
        type: "M75.1 Rotator cuff syndrome",
        isHidden: false,
        sides: [],
      },
      {
        id: 707,
        type: "M47.9 Spondylosis, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 708,
        type: "M22.9 Internal derangement of knee",
        isHidden: false,
        sides: [],
      },
      {
        id: 709,
        type: "M16.9 Osteoarthritis of hip",
        isHidden: true,
        sides: [],
      },
      {
        id: 710,
        type: "M99.02 Segmental and somatic dysfunction of thoracic region",
        isHidden: true,
        sides: [],
      },
    ],
  },
  {
    id: 8,
    title: "Pelvic Pain",
    isHidden: false,
    disorders: [
      {
        id: 801,
        type: "N94.6 Dysmenorrhea, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 802,
        type: "R10.2 Pelvic and perineal pain",
        isHidden: false,
        sides: [],
      },
      {
        id: 803,
        type: "N85.9 Abnormal uterine and vaginal bleeding",
        isHidden: false,
        sides: [],
      },
      {
        id: 804,
        type: "N81.9 Female genital prolapse",
        isHidden: false,
        sides: [],
      },
      {
        id: 805,
        type: "M62.8 Other disorders of muscle",
        isHidden: false,
        sides: [],
      },
      { id: 806, type: "K62.5 Hemorrhoids", isHidden: false, sides: [] },
      { id: 807, type: "N80.9 Endometriosis", isHidden: false, sides: [] },
      {
        id: 808,
        type: "N93.9 Abnormal bleeding from female genital tract",
        isHidden: false,
        sides: [],
      },
      {
        id: 809,
        type: "N89 Vaginitis and vulvovaginitis",
        isHidden: true,
        sides: [],
      },
      {
        id: 810,
        type: "N73.9 Female pelvic inflammatory disease",
        isHidden: true,
        sides: [],
      },
    ],
  },
  {
    id: 9,
    title: "Shoulder Pain",
    isHidden: false,
    disorders: [
      {
        id: 901,
        type: "M75.1 Rotator cuff syndrome",
        isHidden: false,
        sides: [],
      },
      {
        id: 902,
        type: "M75.9 Shoulder lesion, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 903,
        type: "M54.6 Pain in thoracic spine",
        isHidden: false,
        sides: [],
      },
      {
        id: 904,
        type: "M76.1 Patellar tendinitis",
        isHidden: false,
        sides: [],
      },
      {
        id: 905,
        type: "M79.5 Pain in limb, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 906,
        type: "M67.9 Synovial disorder, unspecified",
        isHidden: false,
        sides: [],
      },
      { id: 907, type: "M10.9 Gout, unspecified", isHidden: false, sides: [] },
      {
        id: 908,
        type: "M99.03 Segmental and somatic dysfunction of the shoulder",
        isHidden: false,
        sides: [],
      },
      {
        id: 909,
        type: "M23.8 Other internal derangement of the knee",
        isHidden: true,
        sides: [],
      },
      {
        id: 910,
        type: "M41.8 Other deforming dorsopathies",
        isHidden: true,
        sides: [],
      },
    ],
  },
  {
    id: 10,
    title: "Facial Pain",
    isHidden: true,
    disorders: [
      {
        id: 1001,
        type: "M79.0 Rheumatism, unspecified",
        isHidden: false,
        sides: [],
      },
      { id: 1002, type: "R51 Headache", isHidden: false, sides: [] },
      { id: 1003, type: "G44.2 Cluster headache", isHidden: false, sides: [] },
      { id: 1004, type: "R07.0 Pain in throat", isHidden: false, sides: [] },
      {
        id: 1005,
        type: "K12.0 Stomatitis, unspecified",
        isHidden: false,
        sides: [],
      },
      {
        id: 1006,
        type: "G44.1 Tension-type headache",
        isHidden: false,
        sides: [],
      },
      { id: 1007, type: "M54.2 Cervicalgia", isHidden: false, sides: [] },
      { id: 1008, type: "R04.0 Epistaxis", isHidden: false, sides: [] },
      {
        id: 1009,
        type: "I63.9 Cerebral infarction",
        isHidden: true,
        sides: [],
      },
      { id: 1010, type: "M79.1 Myalgia", isHidden: true, sides: [] },
    ],
  },
];

export const disorderTypes = {
  painTypes,
};
