export const facilitiesData = [
  {
    id: 1,
    facility_name: "Sunrise Medical Center",
    contact_name: "Dr. John Doe",
    address: "123 Main St, New York, NY",
    suite: "Suite 100",
    email: "contact@sunrisemed.com",
    phone: "123-456-7890",
    notify_email_1: "notify1@sunrisemed.com",
    notify_email_2: "notify2@sunrisemed.com",
    fax: "123-456-7891",
    account_type: "hospital",
    status: "active",
    doctors: [
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1005,
        first_name: "James",
        last_name: "Wilson",
        email: "james.wilson@email.com",
        phone: "+1-305-555-0176",
        address: "210 Ocean Dr, Miami, FL",
        company: "Florida 100Medical Group",
        role: "doctor",
        status: "blocked",
        npi: "5678901234",
        apt_number: "37482",
        image: "https://randomuser.me/api/portraits/men/5.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 2,
    facility_name: "Downtown Clinic",
    contact_name: "Dr. Sarah Adams",
    address: "456 Broadway, Los Angeles, CA",
    suite: "Suite 205",
    email: "contact@downtownclinic.com",
    phone: "213-555-0187",
    notify_email_1: "notify1@downtownclinic.com",
    notify_email_2: "notify2@downtownclinic.com",
    fax: "213-555-0188",
    account_type: "clinic",
    status: "active",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1005,
        first_name: "James",
        last_name: "Wilson",
        email: "james.wilson@email.com",
        phone: "+1-305-555-0176",
        address: "210 Ocean Dr, Miami, FL",
        company: "Florida 100Medical Group",
        role: "doctor",
        status: "blocked",
        npi: "5678901234",
        apt_number: "37482",
        image: "https://randomuser.me/api/portraits/men/5.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 3,
    facility_name: "Evergreen Healthcare",
    contact_name: "Dr. James Parker",
    address: "789 Pine St, Seattle, WA",
    suite: "Suite 301",
    email: "contact@evergreenhealth.com",
    phone: "206-555-0123",
    notify_email_1: "notify1@evergreenhealth.com",
    notify_email_2: "notify2@evergreenhealth.com",
    fax: "206-555-0124",
    account_type: "hospital",
    status: "blocked",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 4,
    facility_name: "Metro Labs",
    contact_name: "Dr. Laura Benson",
    address: "101 Maple Ave, Chicago, IL",
    suite: "Suite 450",
    email: "contact@metrolabs.com",
    phone: "312-555-0145",
    notify_email_1: "notify1@metrolabs.com",
    notify_email_2: "notify2@metrolabs.com",
    fax: "312-555-0146",
    account_type: "laboratory",
    status: "active",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 5,
    facility_name: "Westside Family Care",
    contact_name: "Dr. Emily Roberts",
    address: "202 Oak St, Denver, CO",
    suite: "Suite 210",
    email: "contact@westsidecare.com",
    phone: "303-555-0190",
    notify_email_1: "notify1@westsidecare.com",
    notify_email_2: "notify2@westsidecare.com",
    fax: "303-555-0191",
    account_type: "clinic",
    status: "active",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 6,
    facility_name: "City Health Associates",
    contact_name: "Dr. Michael Smith",
    address: "333 Cedar Ln, Austin, TX",
    suite: "Suite 125",
    email: "contact@cityhealth.com",
    phone: "512-555-0172",
    notify_email_1: "notify1@cityhealth.com",
    notify_email_2: "notify2@cityhealth.com",
    fax: "512-555-0173",
    account_type: "specialty center",
    status: "active",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 7,
    facility_name: "Green Valley Medical",
    contact_name: "Dr. Susan Clark",
    address: "555 Spruce St, Phoenix, AZ",
    suite: "Suite 505",
    email: "contact@greenvalleymed.com",
    phone: "602-555-0183",
    notify_email_1: "notify1@greenvalleymed.com",
    notify_email_2: "notify2@greenvalleymed.com",
    fax: "602-555-0184",
    account_type: "rehabilitation",
    status: "blocked",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 8,
    facility_name: "Lakeside Urgent Care",
    contact_name: "Dr. Henry Wilson",
    address: "777 River Rd, Orlando, FL",
    suite: "Suite 220",
    email: "contact@lakesideurgent.com",
    phone: "407-555-0166",
    notify_email_1: "notify1@lakesideurgent.com",
    notify_email_2: "notify2@lakesideurgent.com",
    fax: "407-555-0167",
    account_type: "urgent care",
    status: "active",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 9,
    facility_name: "Summit Specialty Center",
    contact_name: "Dr. Robert Johnson",
    address: "888 Summit St, Boston, MA",
    suite: "Suite 350",
    email: "contact@summitspecialty.com",
    phone: "617-555-0155",
    notify_email_1: "notify1@summitspecialty.com",
    notify_email_2: "notify2@summitspecialty.com",
    fax: "617-555-0156",
    account_type: "specialty center",
    status: "active",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 10,
    facility_name: "Pinecrest Healthcare",
    contact_name: "Dr. Linda Thompson",
    address: "999 Forest Ave, San Francisco, CA",
    suite: "Suite 400",
    email: "contact@pinecresthealth.com",
    phone: "415-555-0195",
    notify_email_1: "notify1@pinecresthealth.com",
    notify_email_2: "notify2@pinecresthealth.com",
    fax: "415-555-0196",
    account_type: "hospital",
    status: "active",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 11,
    facility_name: "Northside Pediatric",
    contact_name: "Dr. Andrew Miller",
    address: "432 Willow St, Houston, TX",
    suite: "Suite 101",
    email: "contact@northsidepeds.com",
    phone: "713-555-0129",
    notify_email_1: "notify1@northsidepeds.com",
    notify_email_2: "notify2@northsidepeds.com",
    fax: "713-555-0130",
    account_type: "clinic",
    status: "blocked",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 12,
    facility_name: "Eastside Family Clinic",
    contact_name: "Dr. Daniel Harris",
    address: "456 Elm St, Philadelphia, PA",
    suite: "Suite 202",
    email: "contact@eastsideclinic.com",
    phone: "215-555-0101",
    notify_email_1: "notify1@eastsideclinic.com",
    notify_email_2: "notify2@eastsideclinic.com",
    fax: "215-555-0102",
    account_type: "clinic",
    status: "active",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 13,
    facility_name: "Oceanview Hospital",
    contact_name: "Dr. Megan Carter",
    address: "789 Coastal Rd, Miami, FL",
    suite: "Suite 310",
    email: "contact@oceanviewhospital.com",
    phone: "305-555-0134",
    notify_email_1: "notify1@oceanviewhospital.com",
    notify_email_2: "notify2@oceanviewhospital.com",
    fax: "305-555-0135",
    account_type: "hospital",
    status: "active",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 14,
    facility_name: "Midtown Diagnostic Center",
    contact_name: "Dr. George Evans",
    address: "321 Main St, Dallas, TX",
    suite: "Suite 415",
    email: "contact@midtowndiagnostics.com",
    phone: "972-555-0148",
    notify_email_1: "notify1@midtowndiagnostics.com",
    notify_email_2: "notify2@midtowndiagnostics.com",
    fax: "972-555-0149",
    account_type: "laboratory",
    status: "blocked",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 15,
    facility_name: "Crescent Valley Health",
    contact_name: "Dr. Olivia Martinez",
    address: "555 Birch St, San Diego, CA",
    suite: "Suite 500",
    email: "contact@crescenthealth.com",
    phone: "619-555-0177",
    notify_email_1: "notify1@crescenthealth.com",
    notify_email_2: "notify2@crescenthealth.com",
    fax: "619-555-0178",
    account_type: "specialty center",
    status: "active",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 16,
    facility_name: "Riverside Medical Group",
    contact_name: "Dr. William Cooper",
    address: "678 Riverway Dr, Nashville, TN",
    suite: "Suite 280",
    email: "contact@riversidemed.com",
    phone: "615-555-0153",
    notify_email_1: "notify1@riversidemed.com",
    notify_email_2: "notify2@riversidemed.com",
    fax: "615-555-0154",
    account_type: "clinic",
    status: "active",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 17,
    facility_name: "West Hills Rehabilitation",
    contact_name: "Dr. Sophia Bennett",
    address: "890 Hillside Ave, Portland, OR",
    suite: "Suite 125",
    email: "contact@westhillsrehab.com",
    phone: "503-555-0162",
    notify_email_1: "notify1@westhillsrehab.com",
    notify_email_2: "notify2@westhillsrehab.com",
    fax: "503-555-0163",
    account_type: "rehabilitation",
    status: "blocked",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 18,
    facility_name: "Bay Area Pediatrics",
    contact_name: "Dr. Ethan Robinson",
    address: "234 Marina Blvd, San Jose, CA",
    suite: "Suite 302",
    email: "contact@bayareapediatrics.com",
    phone: "408-555-0180",
    notify_email_1: "notify1@bayareapediatrics.com",
    notify_email_2: "notify2@bayareapediatrics.com",
    fax: "408-555-0181",
    account_type: "clinic",
    status: "active",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 19,
    facility_name: "Southview Cardiology Center",
    contact_name: "Dr. Natalie Green",
    address: "123 Heart St, Atlanta, GA",
    suite: "Suite 430",
    email: "contact@southviewcardiology.com",
    phone: "404-555-0198",
    notify_email_1: "notify1@southviewcardiology.com",
    notify_email_2: "notify2@southviewcardiology.com",
    fax: "404-555-0199",
    account_type: "specialty center",
    status: "active",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
  {
    id: 20,
    facility_name: "Northridge Orthopedic",
    contact_name: "Dr. Patrick White",
    address: "777 Bone St, Minneapolis, MN",
    suite: "Suite 210",
    email: "contact@northridgeortho.com",
    phone: "612-555-0112",
    notify_email_1: "notify1@northridgeortho.com",
    notify_email_2: "notify2@northridgeortho.com",
    fax: "612-555-0113",
    account_type: "specialty center",
    status: "blocked",
    doctors: [
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1001,
        first_name: "John",
        last_name: "Doe",
        email: "johndoe@email.com",
        phone: "+1-202-555-0173",
        address: "123 Main St, Springfield, IL",
        company: "Springfield Medical Center",
        role: "doctor",
        status: "active",
        npi: "1234567890",
        apt_number: "48293",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
      {
        id: 1003,
        first_name: "Michael",
        last_name: "Brown",
        email: "michael.brown@email.com",
        phone: "+1-415-555-0127",
        address: "789 Oak St, San Francisco, CA",
        company: "Bay Area Medical",
        role: "doctor",
        status: "active",
        npi: "9876543210",
        apt_number: "25931",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        signature:
          "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
      },
    ],
  },
];
