export const patientsData = [
  {
    id: 1,
    first_name: "John",
    last_name: "Doe",
    email: "john.doe@example.com",
    phone: "(555) 123-4567",
    address: "123 Main St",
    apt_number: "10234",
    gender: "Male",
    date_of_birth: "1980-05-15",
    insurance_company: "Blue Cross",
    member_id: "BC123456789",
    reasons: ["Headache", "Dizziness"],
    sensory_symptoms: ["Numbness in hands"],
    ethnicity: "Caucasian",
    ordering_physician: "Dr. Smith",
  },
  {
    id: 2,
    first_name: "Emily",
    last_name: "Johnson",
    email: "emily.johnson@example.com",
    phone: "(555) 987-6543",
    address: "456 Oak Rd",
    apt_number: "45321",
    gender: "Female",
    date_of_birth: "1992-09-24",
    insurance_company: "Aetna",
    member_id: "AT987654321",
    reasons: ["Chest pain", "Shortness of breath"],
    sensory_symptoms: ["No sensory symptoms"],
    ethnicity: "Hispanic",
    ordering_physician: "Dr. Lee",
  },
  {
    id: 3,
    first_name: "Michael",
    last_name: "Brown",
    email: "michael.brown@example.com",
    phone: "(555) 345-6789",
    address: "789 Pine Ln",
    apt_number: "98765",
    gender: "Male",
    date_of_birth: "1975-02-10",
    insurance_company: "United Healthcare",
    member_id: "UH112233445",
    reasons: ["Abdominal pain", "Nausea"],
    sensory_symptoms: ["Dizziness"],
    ethnicity: "African American",
    ordering_physician: "Dr. White",
  },
  {
    id: 4,
    first_name: "Sarah",
    last_name: "Miller",
    email: "sarah.miller@example.com",
    phone: "(555) 678-1234",
    address: "321 Birch Blvd",
    apt_number: "54321",
    gender: "Female",
    date_of_birth: "1988-11-18",
    insurance_company: "Cigna",
    member_id: "CG998877665",
    reasons: ["Joint pain", "Swelling"],
    sensory_symptoms: ["No sensory symptoms"],
    ethnicity: "Asian",
    ordering_physician: "Dr. Green",
  },
  {
    id: 5,
    first_name: "David",
    last_name: "Martinez",
    email: "david.martinez@example.com",
    phone: "(555) 456-7890",
    address: "654 Maple Dr",
    apt_number: "98476",
    gender: "Male",
    date_of_birth: "1990-07-30",
    insurance_company: "Aetna",
    member_id: "AT665544332",
    reasons: ["Back pain", "Sciatica"],
    sensory_symptoms: ["Leg numbness"],
    ethnicity: "Hispanic",
    ordering_physician: "Dr. Black",
  },
  {
    id: 6,
    first_name: "Olivia",
    last_name: "Davis",
    email: "olivia.davis@example.com",
    phone: "(555) 234-5678",
    address: "890 Cedar St",
    apt_number: "67945",
    gender: "Female",
    date_of_birth: "1995-03-21",
    insurance_company: "Humana",
    member_id: "HU445566778",
    reasons: ["Leg pain", "Cramps"],
    sensory_symptoms: ["Tingling in feet"],
    ethnicity: "Caucasian",
    ordering_physician: "Dr. Wilson",
  },
  {
    id: 7,
    first_name: "James",
    last_name: "Wilson",
    email: "james.wilson@example.com",
    phone: "(555) 567-8901",
    address: "234 Elm Ave",
    apt_number: "56789",
    gender: "Male",
    date_of_birth: "1983-12-12",
    insurance_company: "Blue Shield",
    member_id: "BS223344556",
    reasons: ["Chest pain", "Fatigue"],
    sensory_symptoms: ["None"],
    ethnicity: "African American",
    ordering_physician: "Dr. Adams",
  },
  {
    id: 8,
    first_name: "Isabella",
    last_name: "Thomas",
    email: "isabella.thomas@example.com",
    phone: "(555) 678-9876",
    address: "135 Willow Dr",
    apt_number: "87654",
    gender: "Female",
    date_of_birth: "1998-08-22",
    insurance_company: "Cigna",
    member_id: "CG778899001",
    reasons: ["Abdominal discomfort", "Bloating"],
    sensory_symptoms: ["No sensory symptoms"],
    ethnicity: "White",
    ordering_physician: "Dr. Mitchell",
  },
  {
    id: 9,
    first_name: "Matthew",
    last_name: "Anderson",
    email: "matthew.anderson@example.com",
    phone: "(555) 890-1234",
    address: "567 Oak Ln",
    apt_number: "76543",
    gender: "Male",
    date_of_birth: "1993-04-05",
    insurance_company: "United Healthcare",
    member_id: "UH443322110",
    reasons: ["Back pain", "Muscle strain"],
    sensory_symptoms: ["No sensory symptoms"],
    ethnicity: "Caucasian",
    ordering_physician: "Dr. Robinson",
  },
  {
    id: 10,
    first_name: "Sophia",
    last_name: "Garcia",
    email: "sophia.garcia@example.com",
    phone: "(555) 234-5678",
    address: "432 Pine Ave",
    apt_number: "54320",
    gender: "Female",
    date_of_birth: "1999-01-17",
    insurance_company: "Humana",
    member_id: "HU123456789",
    reasons: ["Knee pain", "Swelling"],
    sensory_symptoms: ["No sensory symptoms"],
    ethnicity: "Hispanic",
    ordering_physician: "Dr. Clark",
  },
  {
    id: 11,
    first_name: "Liam",
    last_name: "Moore",
    email: "liam.moore@example.com",
    phone: "(555) 987-6543",
    address: "321 Birch Blvd",
    apt_number: "65321",
    gender: "Male",
    date_of_birth: "1985-02-28",
    insurance_company: "Blue Cross",
    member_id: "BC112233445",
    reasons: ["Hip pain", "Limping"],
    sensory_symptoms: ["No sensory symptoms"],
    ethnicity: "Caucasian",
    ordering_physician: "Dr. Harris",
  },
  {
    id: 12,
    first_name: "Ava",
    last_name: "Martinez",
    email: "ava.martinez@example.com",
    phone: "(555) 876-5432",
    address: "567 Cedar Rd",
    apt_number: "76501",
    gender: "Female",
    date_of_birth: "1994-10-05",
    insurance_company: "Aetna",
    member_id: "AT998877665",
    reasons: ["Shoulder pain", "Restricted movement"],
    sensory_symptoms: ["No sensory symptoms"],
    ethnicity: "Hispanic",
    ordering_physician: "Dr. Jackson",
  },
  {
    id: 13,
    first_name: "Benjamin",
    last_name: "Taylor",
    email: "benjamin.taylor@example.com",
    phone: "(555) 567-2345",
    address: "654 Oak Blvd",
    apt_number: "12345",
    gender: "Male",
    date_of_birth: "1982-06-11",
    insurance_company: "United Healthcare",
    member_id: "UH667788990",
    reasons: ["Foot pain", "Swelling"],
    sensory_symptoms: ["No sensory symptoms"],
    ethnicity: "African American",
    ordering_physician: "Dr. Carter",
  },
  {
    id: 14,
    first_name: "Mia",
    last_name: "Harris",
    email: "mia.harris@example.com",
    phone: "(555) 345-7890",
    address: "890 Pine St",
    apt_number: "43210",
    gender: "Female",
    date_of_birth: "1997-12-20",
    insurance_company: "Humana",
    member_id: "HU223344556",
    reasons: ["Knee pain", "Difficulty walking"],
    sensory_symptoms: ["Tingling in feet"],
    ethnicity: "Caucasian",
    ordering_physician: "Dr. Moore",
  },
  {
    id: 15,
    first_name: "Ethan",
    last_name: "Nelson",
    email: "ethan.nelson@example.com",
    phone: "(555) 234-8901",
    address: "123 Maple St",
    apt_number: "34567",
    gender: "Male",
    date_of_birth: "1991-01-25",
    insurance_company: "Blue Shield",
    member_id: "BS223355667",
    reasons: ["Wrist pain", "Swelling"],
    sensory_symptoms: ["No sensory symptoms"],
    ethnicity: "Asian",
    ordering_physician: "Dr. Turner",
  },
  {
    id: 16,
    first_name: "Charlotte",
    last_name: "Lopez",
    email: "charlotte.lopez@example.com",
    phone: "(555) 654-3210",
    address: "456 Cedar St",
    apt_number: "87632",
    gender: "Female",
    date_of_birth: "1996-07-12",
    insurance_company: "Aetna",
    member_id: "AT112233445",
    reasons: ["Neck pain", "Stiffness"],
    sensory_symptoms: ["No sensory symptoms"],
    ethnicity: "Hispanic",
    ordering_physician: "Dr. Martinez",
  },
  {
    id: 17,
    first_name: "Alexander",
    last_name: "Walker",
    email: "alexander.walker@example.com",
    phone: "(555) 876-2109",
    address: "890 Spruce Ln",
    apt_number: "90876",
    gender: "Male",
    date_of_birth: "1980-03-10",
    insurance_company: "Cigna",
    member_id: "CG556677889",
    reasons: ["Back pain", "Muscle tension"],
    sensory_symptoms: ["No sensory symptoms"],
    ethnicity: "White",
    ordering_physician: "Dr. Wright",
  },
  {
    id: 18,
    first_name: "Grace",
    last_name: "Perez",
    email: "grace.perez@example.com",
    phone: "(555) 432-7890",
    address: "123 Redwood Ave",
    apt_number: "67890",
    gender: "Female",
    date_of_birth: "1992-08-14",
    insurance_company: "United Healthcare",
    member_id: "UH998877665",
    reasons: ["Fatigue", "Dizziness"],
    sensory_symptoms: ["Numbness in fingers"],
    ethnicity: "Hispanic",
    ordering_physician: "Dr. Evans",
  },
  {
    id: 19,
    first_name: "Daniel",
    last_name: "Young",
    email: "daniel.young@example.com",
    phone: "(555) 321-4567",
    address: "543 Oak St",
    apt_number: "23456",
    gender: "Male",
    date_of_birth: "1978-05-22",
    insurance_company: "Blue Cross",
    member_id: "BC778899001",
    reasons: ["Hip pain", "Stiffness"],
    sensory_symptoms: ["No sensory symptoms"],
    ethnicity: "Caucasian",
    ordering_physician: "Dr. Brooks",
  },
  {
    id: 20,
    first_name: "Sofia",
    last_name: "King",
    email: "sofia.king@example.com",
    phone: "(555) 654-9876",
    address: "321 Elm St",
    apt_number: "56789",
    gender: "Female",
    date_of_birth: "1990-09-30",
    insurance_company: "Humana",
    member_id: "HU123443322",
    reasons: ["Joint pain", "Swelling"],
    sensory_symptoms: ["No sensory symptoms"],
    ethnicity: "African American",
    ordering_physician: "Dr. Jenkins",
  },
];
