export const testsData = [
  {
    report_no: "2470",
    status: "Collected",
    ordering_provider: "Bay Area Medical",
    ordering_physician: "Dr. Michael",
    facility: "Downtown Clinic",
    cpts: ["41612", "88005"],
    icds: ["G60.3", "G455.2"],
    apply_date: "2025-01-02T17:30:00",
    report_date: "2025-01-02T17:30:00",
    patient: {
      id: 20,
      first_name: "Sofia",
      last_name: "King",
      email: "sofia.king@example.com",
      phone: "(555) 654-9876",
      address: "321 Elm St",
      apt_number: "56789",
      gender: "Female",
      date_of_birth: "1990-09-30",
      insurance_company: "Humana",
      member_id: "HU123443322",
      reasons: ["Joint pain", "Swelling"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "African American",
      ordering_physician: "Dr. Jenkins",
    },
    disorder_observation: {
      metabolic: [
        {
          code: "E03.9",
          description: "Hypothyroidism, unspecified",
        },
        {
          code: "E10.40",
          description: "Type 1 DM with diabetic neuropathy, unspecified",
        },
      ],
    },
    reason_for_skin_biopsy: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    communication_with_patient: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    clinical_symptoms: {
      neck_pain: [
        {
          description: "Spinal stenosis, cervical region",
          code: "M48.02",
          side: "Left",
        },
        {
          description: "Cervicalgia",
          code: "M54.2",
          side: "Right",
        },
      ],
      leg_pain: [
        {
          description: "Coldness in your neck",
          side: "Both",
        },
        {
          description: "Discomfort in your neck wakes you up at night",
          side: "Right",
        },
      ],
    },
    biopsy_samples: [
      {
        location: "Proximal Arm",
        abbreviation: "PA",
        side: "Left",
        specimen_id: "61961465165",
      },
      {
        location: "Proximal Thigh",
        abbreviation: "PT",
        side: "Left",
        specimen_id: "61961465166",
      },
      {
        location: "Calf",
        abbreviation: "C",
        side: "Left",
        specimen_id: "61961465167",
      },
      {
        location: "Ankle",
        abbreviation: "A",
        side: "Left",
        specimen_id: "61961465168",
      },
    ],
    documents: ["MPS-SOAP NOTE", "MPS-Test Testing-REO-H4NPX"],
    pathologist_section: {
      final_microscopic_diagnosis: {
        normal: ">9",
        borderline: "7.2-8.9",
        mild: "3.9-7.1",
        moderate: "2.1-3.8",
        severe: "0-2",
      },
      samples: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
      ],
      microscopic_examination: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      gross_description: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      comments: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          comment: "Left Distal Thigh Diagnosis",
        },
      ],
      biopsy_findings: {
        number_of_fibers: 2,
        nerve_fiber_density: "Consistent with...",
        neuropathy_type: "Length-dependent neuropathy",
      },
      notes: [
        {
          text: "The biopsies demonstrate...",
        },
        {
          text: "The biopsies demonstrate...",
        },
      ],
    },
  },
  {
    report_no: "2471",
    status: "Send to Histology",
    ordering_provider: "South Area Clinic",
    ordering_physician: "Dr. Jackson",
    facility: "Downtown Clinic",
    cpts: ["41612", "88005"],
    icds: ["G60.3", "G455.2"],
    apply_date: "2025-01-02T17:30:00",
    report_date: "2025-01-02T17:30:00",
    patient: {
      id: 20,
      first_name: "Sofia",
      last_name: "King",
      email: "sofia.king@example.com",
      phone: "(555) 654-9876",
      address: "321 Elm St",
      apt_number: "56789",
      gender: "Female",
      date_of_birth: "1990-09-30",
      insurance_company: "Humana",
      member_id: "HU123443322",
      reasons: ["Joint pain", "Swelling"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "African American",
      ordering_physician: "Dr. Jenkins",
    },
    disorder_observation: {
      metabolic: [
        {
          code: "E03.9",
          description: "Hypothyroidism, unspecified",
        },
        {
          code: "E10.40",
          description: "Type 1 DM with diabetic neuropathy, unspecified",
        },
      ],
    },
    reason_for_skin_biopsy: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    communication_with_patient: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    clinical_symptoms: {
      neck_pain: [
        {
          description: "Spinal stenosis, cervical region",
          code: "M48.02",
          side: "Left",
        },
        {
          description: "Cervicalgia",
          code: "M54.2",
          side: "Right",
        },
      ],
      leg_pain: [
        {
          description: "Coldness in your neck",
          side: "Both",
        },
        {
          description: "Discomfort in your neck wakes you up at night",
          side: "Right",
        },
      ],
    },
    biopsy_samples: [
      {
        location: "Proximal Arm",
        abbreviation: "PA",
        side: "Left",
        specimen_id: "61961465165",
      },
      {
        location: "Proximal Thigh",
        abbreviation: "PT",
        side: "Left",
        specimen_id: "61961465166",
      },
      {
        location: "Calf",
        abbreviation: "C",
        side: "Left",
        specimen_id: "61961465167",
      },
      {
        location: "Ankle",
        abbreviation: "A",
        side: "Left",
        specimen_id: "61961465168",
      },
    ],
    documents: ["MPS-SOAP NOTE", "MPS-Test Testing-REO-H4NPX"],
    pathologist_section: {
      final_microscopic_diagnosis: {
        normal: ">9",
        borderline: "7.2-8.9",
        mild: "3.9-7.1",
        moderate: "2.1-3.8",
        severe: "0-2",
      },
      samples: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
      ],
      microscopic_examination: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      gross_description: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      comments: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          comment: "Left Distal Thigh Diagnosis",
        },
      ],
      biopsy_findings: {
        number_of_fibers: 2,
        nerve_fiber_density: "Consistent with...",
        neuropathy_type: "Length-dependent neuropathy",
      },
      notes: [
        {
          text: "The biopsies demonstrate...",
        },
        {
          text: "The biopsies demonstrate...",
        },
      ],
    },
  },
  {
    report_no: "2473",
    status: "Collected",
    ordering_provider: "Northern Lab",
    ordering_physician: "Dr. Jacobison",
    facility: "Hispil Clinic",
    cpts: ["41612", "88005"],
    icds: ["G60.3", "G455.2"],
    apply_date: "2025-01-02T17:30:00",
    report_date: "2025-01-02T17:30:00",
    patient: {
      id: 20,
      first_name: "Sofia",
      last_name: "King",
      email: "sofia.king@example.com",
      phone: "(555) 654-9876",
      address: "321 Elm St",
      apt_number: "56789",
      gender: "Female",
      date_of_birth: "1990-09-30",
      insurance_company: "Humana",
      member_id: "HU123443322",
      reasons: ["Joint pain", "Swelling"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "African American",
      ordering_physician: "Dr. Jenkins",
    },
    disorder_observation: {
      metabolic: [
        {
          code: "E03.9",
          description: "Hypothyroidism, unspecified",
        },
        {
          code: "E10.40",
          description: "Type 1 DM with diabetic neuropathy, unspecified",
        },
      ],
    },
    reason_for_skin_biopsy: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    communication_with_patient: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    clinical_symptoms: {
      neck_pain: [
        {
          description: "Spinal stenosis, cervical region",
          code: "M48.02",
          side: "Left",
        },
        {
          description: "Cervicalgia",
          code: "M54.2",
          side: "Right",
        },
      ],
      leg_pain: [
        {
          description: "Coldness in your neck",
          side: "Both",
        },
        {
          description: "Discomfort in your neck wakes you up at night",
          side: "Right",
        },
      ],
    },
    biopsy_samples: [
      {
        location: "Proximal Arm",
        abbreviation: "PA",
        side: "Left",
        specimen_id: "61961465165",
      },
      {
        location: "Proximal Thigh",
        abbreviation: "PT",
        side: "Left",
        specimen_id: "61961465166",
      },
      {
        location: "Calf",
        abbreviation: "C",
        side: "Left",
        specimen_id: "61961465167",
      },
      {
        location: "Ankle",
        abbreviation: "A",
        side: "Left",
        specimen_id: "61961465168",
      },
    ],
    documents: ["MPS-SOAP NOTE", "MPS-Test Testing-REO-H4NPX"],
    pathologist_section: {
      final_microscopic_diagnosis: {
        normal: ">9",
        borderline: "7.2-8.9",
        mild: "3.9-7.1",
        moderate: "2.1-3.8",
        severe: "0-2",
      },
      samples: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
      ],
      microscopic_examination: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      gross_description: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      comments: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          comment: "Left Distal Thigh Diagnosis",
        },
      ],
      biopsy_findings: {
        number_of_fibers: 2,
        nerve_fiber_density: "Consistent with...",
        neuropathy_type: "Length-dependent neuropathy",
      },
      notes: [
        {
          text: "The biopsies demonstrate...",
        },
        {
          text: "The biopsies demonstrate...",
        },
      ],
    },
  },
  {
    report_no: "2474",
    status: "Send to Histology",
    ordering_provider: "Central Medical Center",
    ordering_physician: "Dr. Luis Del",
    facility: "Southern Hospital",
    cpts: ["41612", "88005"],
    icds: ["G60.3", "G455.2"],
    apply_date: "2025-01-02T17:30:00",
    report_date: "2025-01-02T17:30:00",
    patient: {
      id: 20,
      first_name: "Sofia",
      last_name: "King",
      email: "sofia.king@example.com",
      phone: "(555) 654-9876",
      address: "321 Elm St",
      apt_number: "56789",
      gender: "Female",
      date_of_birth: "1990-09-30",
      insurance_company: "Humana",
      member_id: "HU123443322",
      reasons: ["Joint pain", "Swelling"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "African American",
      ordering_physician: "Dr. Jenkins",
    },
    disorder_observation: {
      metabolic: [
        {
          code: "E03.9",
          description: "Hypothyroidism, unspecified",
        },
        {
          code: "E10.40",
          description: "Type 1 DM with diabetic neuropathy, unspecified",
        },
      ],
    },
    reason_for_skin_biopsy: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    communication_with_patient: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    clinical_symptoms: {
      neck_pain: [
        {
          description: "Spinal stenosis, cervical region",
          code: "M48.02",
          side: "Left",
        },
        {
          description: "Cervicalgia",
          code: "M54.2",
          side: "Right",
        },
      ],
      leg_pain: [
        {
          description: "Coldness in your neck",
          side: "Both",
        },
        {
          description: "Discomfort in your neck wakes you up at night",
          side: "Right",
        },
      ],
    },
    biopsy_samples: [
      {
        location: "Proximal Arm",
        abbreviation: "PA",
        side: "Left",
        specimen_id: "61961465165",
      },
      {
        location: "Proximal Thigh",
        abbreviation: "PT",
        side: "Left",
        specimen_id: "61961465166",
      },
      {
        location: "Calf",
        abbreviation: "C",
        side: "Left",
        specimen_id: "61961465167",
      },
      {
        location: "Ankle",
        abbreviation: "A",
        side: "Left",
        specimen_id: "61961465168",
      },
    ],
    documents: ["MPS-SOAP NOTE", "MPS-Test Testing-REO-H4NPX"],
    pathologist_section: {
      final_microscopic_diagnosis: {
        normal: ">9",
        borderline: "7.2-8.9",
        mild: "3.9-7.1",
        moderate: "2.1-3.8",
        severe: "0-2",
      },
      samples: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
      ],
      microscopic_examination: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      gross_description: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      comments: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          comment: "Left Distal Thigh Diagnosis",
        },
      ],
      biopsy_findings: {
        number_of_fibers: 2,
        nerve_fiber_density: "Consistent with...",
        neuropathy_type: "Length-dependent neuropathy",
      },
      notes: [
        {
          text: "The biopsies demonstrate...",
        },
        {
          text: "The biopsies demonstrate...",
        },
      ],
    },
  },
  {
    report_no: "2405",
    status: "Ready for Pathology",
    ordering_provider: "Bay Area Medical",
    ordering_physician: "Dr. Michael",
    facility: "Downtown Clinic",
    cpts: ["41612", "88005"],
    icds: ["G60.3", "G455.2"],
    apply_date: "2025-01-02T17:30:00",
    report_date: "2025-01-02T17:30:00",
    patient: {
      id: 20,
      first_name: "Sofia",
      last_name: "King",
      email: "sofia.king@example.com",
      phone: "(555) 654-9876",
      address: "321 Elm St",
      apt_number: "56789",
      gender: "Female",
      date_of_birth: "1990-09-30",
      insurance_company: "Humana",
      member_id: "HU123443322",
      reasons: ["Joint pain", "Swelling"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "African American",
      ordering_physician: "Dr. Jenkins",
    },
    disorder_observation: {
      metabolic: [
        {
          code: "E03.9",
          description: "Hypothyroidism, unspecified",
        },
        {
          code: "E10.40",
          description: "Type 1 DM with diabetic neuropathy, unspecified",
        },
      ],
    },
    reason_for_skin_biopsy: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    communication_with_patient: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    clinical_symptoms: {
      neck_pain: [
        {
          description: "Spinal stenosis, cervical region",
          code: "M48.02",
          side: "Left",
        },
        {
          description: "Cervicalgia",
          code: "M54.2",
          side: "Right",
        },
      ],
      leg_pain: [
        {
          description: "Coldness in your neck",
          side: "Both",
        },
        {
          description: "Discomfort in your neck wakes you up at night",
          side: "Right",
        },
      ],
    },
    biopsy_samples: [
      {
        location: "Proximal Arm",
        abbreviation: "PA",
        side: "Left",
        specimen_id: "61961465165",
      },
      {
        location: "Proximal Thigh",
        abbreviation: "PT",
        side: "Left",
        specimen_id: "61961465166",
      },
      {
        location: "Calf",
        abbreviation: "C",
        side: "Left",
        specimen_id: "61961465167",
      },
      {
        location: "Ankle",
        abbreviation: "A",
        side: "Left",
        specimen_id: "61961465168",
      },
    ],
    documents: ["MPS-SOAP NOTE", "MPS-Test Testing-REO-H4NPX"],
    pathologist_section: {
      final_microscopic_diagnosis: {
        normal: ">9",
        borderline: "7.2-8.9",
        mild: "3.9-7.1",
        moderate: "2.1-3.8",
        severe: "0-2",
      },
      samples: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
      ],
      microscopic_examination: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      gross_description: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      comments: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          comment: "Left Distal Thigh Diagnosis",
        },
      ],
      biopsy_findings: {
        number_of_fibers: 2,
        nerve_fiber_density: "Consistent with...",
        neuropathy_type: "Length-dependent neuropathy",
      },
      notes: [
        {
          text: "The biopsies demonstrate...",
        },
        {
          text: "The biopsies demonstrate...",
        },
      ],
    },
  },
  {
    report_no: "2406",
    status: "Final",
    ordering_provider: "California State Hospital",
    ordering_physician: "Dr. Zimmerna",
    facility: "Downtown Clinic",
    cpts: ["41612", "88005"],
    icds: ["G60.3", "G455.2"],
    apply_date: "2025-01-02T17:30:00",
    report_date: "2025-01-02T17:30:00",
    patient: {
      id: 20,
      first_name: "Sofia",
      last_name: "King",
      email: "sofia.king@example.com",
      phone: "(555) 654-9876",
      address: "321 Elm St",
      apt_number: "56789",
      gender: "Female",
      date_of_birth: "1990-09-30",
      insurance_company: "Humana",
      member_id: "HU123443322",
      reasons: ["Joint pain", "Swelling"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "African American",
      ordering_physician: "Dr. Jenkins",
    },
    disorder_observation: {
      metabolic: [
        {
          code: "E03.9",
          description: "Hypothyroidism, unspecified",
        },
        {
          code: "E10.40",
          description: "Type 1 DM with diabetic neuropathy, unspecified",
        },
      ],
    },
    reason_for_skin_biopsy: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    communication_with_patient: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    clinical_symptoms: {
      neck_pain: [
        {
          description: "Spinal stenosis, cervical region",
          code: "M48.02",
          side: "Left",
        },
        {
          description: "Cervicalgia",
          code: "M54.2",
          side: "Right",
        },
      ],
      leg_pain: [
        {
          description: "Coldness in your neck",
          side: "Both",
        },
        {
          description: "Discomfort in your neck wakes you up at night",
          side: "Right",
        },
      ],
    },
    biopsy_samples: [
      {
        location: "Proximal Arm",
        abbreviation: "PA",
        side: "Left",
        specimen_id: "61961465165",
      },
      {
        location: "Proximal Thigh",
        abbreviation: "PT",
        side: "Left",
        specimen_id: "61961465166",
      },
      {
        location: "Calf",
        abbreviation: "C",
        side: "Left",
        specimen_id: "61961465167",
      },
      {
        location: "Ankle",
        abbreviation: "A",
        side: "Left",
        specimen_id: "61961465168",
      },
    ],
    documents: ["MPS-SOAP NOTE", "MPS-Test Testing-REO-H4NPX"],
    pathologist_section: {
      final_microscopic_diagnosis: {
        normal: ">9",
        borderline: "7.2-8.9",
        mild: "3.9-7.1",
        moderate: "2.1-3.8",
        severe: "0-2",
      },
      samples: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
      ],
      microscopic_examination: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      gross_description: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      comments: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          comment: "Left Distal Thigh Diagnosis",
        },
      ],
      biopsy_findings: {
        number_of_fibers: 2,
        nerve_fiber_density: "Consistent with...",
        neuropathy_type: "Length-dependent neuropathy",
      },
      notes: [
        {
          text: "The biopsies demonstrate...",
        },
        {
          text: "The biopsies demonstrate...",
        },
      ],
    },
  },
  {
    report_no: "2407",
    status: "Collected",
    ordering_provider: "California State Clinic",
    ordering_physician: "Dr. Solieth Bel",
    facility: "East Luis Clinic",
    cpts: ["41612", "88005"],
    icds: ["G60.3", "G455.2"],
    apply_date: "2025-01-02T17:30:00",
    report_date: "2025-01-02T17:30:00",
    patient: {
      id: 20,
      first_name: "Sofia",
      last_name: "King",
      email: "sofia.king@example.com",
      phone: "(555) 654-9876",
      address: "321 Elm St",
      apt_number: "56789",
      gender: "Female",
      date_of_birth: "1990-09-30",
      insurance_company: "Humana",
      member_id: "HU123443322",
      reasons: ["Joint pain", "Swelling"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "African American",
      ordering_physician: "Dr. Jenkins",
    },
    disorder_observation: {
      metabolic: [
        {
          code: "E03.9",
          description: "Hypothyroidism, unspecified",
        },
        {
          code: "E10.40",
          description: "Type 1 DM with diabetic neuropathy, unspecified",
        },
      ],
    },
    reason_for_skin_biopsy: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    communication_with_patient: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    clinical_symptoms: {
      neck_pain: [
        {
          description: "Spinal stenosis, cervical region",
          code: "M48.02",
          side: "Left",
        },
        {
          description: "Cervicalgia",
          code: "M54.2",
          side: "Right",
        },
      ],
      leg_pain: [
        {
          description: "Coldness in your neck",
          side: "Both",
        },
        {
          description: "Discomfort in your neck wakes you up at night",
          side: "Right",
        },
      ],
    },
    biopsy_samples: [
      {
        location: "Proximal Arm",
        abbreviation: "PA",
        side: "Left",
        specimen_id: "61961465165",
      },
      {
        location: "Proximal Thigh",
        abbreviation: "PT",
        side: "Left",
        specimen_id: "61961465166",
      },
      {
        location: "Calf",
        abbreviation: "C",
        side: "Left",
        specimen_id: "61961465167",
      },
      {
        location: "Ankle",
        abbreviation: "A",
        side: "Left",
        specimen_id: "61961465168",
      },
    ],
    documents: ["MPS-SOAP NOTE", "MPS-Test Testing-REO-H4NPX"],
    pathologist_section: {
      final_microscopic_diagnosis: {
        normal: ">9",
        borderline: "7.2-8.9",
        mild: "3.9-7.1",
        moderate: "2.1-3.8",
        severe: "0-2",
      },
      samples: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
      ],
      microscopic_examination: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      gross_description: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      comments: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          comment: "Left Distal Thigh Diagnosis",
        },
      ],
      biopsy_findings: {
        number_of_fibers: 2,
        nerve_fiber_density: "Consistent with...",
        neuropathy_type: "Length-dependent neuropathy",
      },
      notes: [
        {
          text: "The biopsies demonstrate...",
        },
        {
          text: "The biopsies demonstrate...",
        },
      ],
    },
  },
  {
    report_no: "2408",
    status: "Send to Histology",
    ordering_provider: "California State Hospital",
    ordering_physician: "Dr. Zimmerna",
    facility: "Downtown Clinic",
    cpts: ["41612", "88005"],
    icds: ["G60.3", "G455.2"],
    apply_date: "2025-01-02T17:30:00",
    report_date: "2025-01-02T17:30:00",
    patient: {
      id: 20,
      first_name: "Sofia",
      last_name: "King",
      email: "sofia.king@example.com",
      phone: "(555) 654-9876",
      address: "321 Elm St",
      apt_number: "56789",
      gender: "Female",
      date_of_birth: "1990-09-30",
      insurance_company: "Humana",
      member_id: "HU123443322",
      reasons: ["Joint pain", "Swelling"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "African American",
      ordering_physician: "Dr. Jenkins",
    },
    disorder_observation: {
      metabolic: [
        {
          code: "E03.9",
          description: "Hypothyroidism, unspecified",
        },
        {
          code: "E10.40",
          description: "Type 1 DM with diabetic neuropathy, unspecified",
        },
      ],
    },
    reason_for_skin_biopsy: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    communication_with_patient: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    clinical_symptoms: {
      neck_pain: [
        {
          description: "Spinal stenosis, cervical region",
          code: "M48.02",
          side: "Left",
        },
        {
          description: "Cervicalgia",
          code: "M54.2",
          side: "Right",
        },
      ],
      leg_pain: [
        {
          description: "Coldness in your neck",
          side: "Both",
        },
        {
          description: "Discomfort in your neck wakes you up at night",
          side: "Right",
        },
      ],
    },
    biopsy_samples: [
      {
        location: "Proximal Arm",
        abbreviation: "PA",
        side: "Left",
        specimen_id: "61961465165",
      },
      {
        location: "Proximal Thigh",
        abbreviation: "PT",
        side: "Left",
        specimen_id: "61961465166",
      },
      {
        location: "Calf",
        abbreviation: "C",
        side: "Left",
        specimen_id: "61961465167",
      },
      {
        location: "Ankle",
        abbreviation: "A",
        side: "Left",
        specimen_id: "61961465168",
      },
    ],
    documents: ["MPS-SOAP NOTE", "MPS-Test Testing-REO-H4NPX"],
    pathologist_section: {
      final_microscopic_diagnosis: {
        normal: ">9",
        borderline: "7.2-8.9",
        mild: "3.9-7.1",
        moderate: "2.1-3.8",
        severe: "0-2",
      },
      samples: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
      ],
      microscopic_examination: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      gross_description: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      comments: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          comment: "Left Distal Thigh Diagnosis",
        },
      ],
      biopsy_findings: {
        number_of_fibers: 2,
        nerve_fiber_density: "Consistent with...",
        neuropathy_type: "Length-dependent neuropathy",
      },
      notes: [
        {
          text: "The biopsies demonstrate...",
        },
        {
          text: "The biopsies demonstrate...",
        },
      ],
    },
  },
  {
    report_no: "2409",
    status: "Ready for Pathology",
    ordering_provider: "Northern Lab",
    ordering_physician: "Dr. Zimmerna",
    facility: "Southern Hospital",
    cpts: ["41612", "88005"],
    icds: ["G60.3", "G455.2"],
    apply_date: "2025-01-02T17:30:00",
    report_date: "2025-01-02T17:30:00",
    patient: {
      id: 20,
      first_name: "Sofia",
      last_name: "King",
      email: "sofia.king@example.com",
      phone: "(555) 654-9876",
      address: "321 Elm St",
      apt_number: "56789",
      gender: "Female",
      date_of_birth: "1990-09-30",
      insurance_company: "Humana",
      member_id: "HU123443322",
      reasons: ["Joint pain", "Swelling"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "African American",
      ordering_physician: "Dr. Jenkins",
    },
    disorder_observation: {
      metabolic: [
        {
          code: "E03.9",
          description: "Hypothyroidism, unspecified",
        },
        {
          code: "E10.40",
          description: "Type 1 DM with diabetic neuropathy, unspecified",
        },
      ],
    },
    reason_for_skin_biopsy: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    communication_with_patient: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    clinical_symptoms: {
      neck_pain: [
        {
          description: "Spinal stenosis, cervical region",
          code: "M48.02",
          side: "Left",
        },
        {
          description: "Cervicalgia",
          code: "M54.2",
          side: "Right",
        },
      ],
      leg_pain: [
        {
          description: "Coldness in your neck",
          side: "Both",
        },
        {
          description: "Discomfort in your neck wakes you up at night",
          side: "Right",
        },
      ],
    },
    biopsy_samples: [
      {
        location: "Proximal Arm",
        abbreviation: "PA",
        side: "Left",
        specimen_id: "61961465165",
      },
      {
        location: "Proximal Thigh",
        abbreviation: "PT",
        side: "Left",
        specimen_id: "61961465166",
      },
      {
        location: "Calf",
        abbreviation: "C",
        side: "Left",
        specimen_id: "61961465167",
      },
      {
        location: "Ankle",
        abbreviation: "A",
        side: "Left",
        specimen_id: "61961465168",
      },
    ],
    documents: ["MPS-SOAP NOTE", "MPS-Test Testing-REO-H4NPX"],
    pathologist_section: {
      final_microscopic_diagnosis: {
        normal: ">9",
        borderline: "7.2-8.9",
        mild: "3.9-7.1",
        moderate: "2.1-3.8",
        severe: "0-2",
      },
      samples: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
      ],
      microscopic_examination: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      gross_description: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      comments: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          comment: "Left Distal Thigh Diagnosis",
        },
      ],
      biopsy_findings: {
        number_of_fibers: 2,
        nerve_fiber_density: "Consistent with...",
        neuropathy_type: "Length-dependent neuropathy",
      },
      notes: [
        {
          text: "The biopsies demonstrate...",
        },
        {
          text: "The biopsies demonstrate...",
        },
      ],
    },
  },
  {
    report_no: "2410",
    status: "Final",
    ordering_provider: "California State Hospital",
    ordering_physician: "Dr. Zimmerna",
    facility: "Downtown Clinic",
    cpts: ["41612", "88005"],
    icds: ["G60.3", "G455.2"],
    apply_date: "2025-01-02T17:30:00",
    report_date: "2025-01-02T17:30:00",
    patient: {
      id: 20,
      first_name: "Sofia",
      last_name: "King",
      email: "sofia.king@example.com",
      phone: "(555) 654-9876",
      address: "321 Elm St",
      apt_number: "56789",
      gender: "Female",
      date_of_birth: "1990-09-30",
      insurance_company: "Humana",
      member_id: "HU123443322",
      reasons: ["Joint pain", "Swelling"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "African American",
      ordering_physician: "Dr. Jenkins",
    },
    disorder_observation: {
      metabolic: [
        {
          code: "E03.9",
          description: "Hypothyroidism, unspecified",
        },
        {
          code: "E10.40",
          description: "Type 1 DM with diabetic neuropathy, unspecified",
        },
      ],
    },
    reason_for_skin_biopsy: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    communication_with_patient: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    clinical_symptoms: {
      neck_pain: [
        {
          description: "Spinal stenosis, cervical region",
          code: "M48.02",
          side: "Left",
        },
        {
          description: "Cervicalgia",
          code: "M54.2",
          side: "Right",
        },
      ],
      leg_pain: [
        {
          description: "Coldness in your neck",
          side: "Both",
        },
        {
          description: "Discomfort in your neck wakes you up at night",
          side: "Right",
        },
      ],
    },
    biopsy_samples: [
      {
        location: "Proximal Arm",
        abbreviation: "PA",
        side: "Left",
        specimen_id: "61961465165",
      },
      {
        location: "Proximal Thigh",
        abbreviation: "PT",
        side: "Left",
        specimen_id: "61961465166",
      },
      {
        location: "Calf",
        abbreviation: "C",
        side: "Left",
        specimen_id: "61961465167",
      },
      {
        location: "Ankle",
        abbreviation: "A",
        side: "Left",
        specimen_id: "61961465168",
      },
    ],
    documents: ["MPS-SOAP NOTE", "MPS-Test Testing-REO-H4NPX"],
    pathologist_section: {
      final_microscopic_diagnosis: {
        normal: ">9",
        borderline: "7.2-8.9",
        mild: "3.9-7.1",
        moderate: "2.1-3.8",
        severe: "0-2",
      },
      samples: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
      ],
      microscopic_examination: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      gross_description: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      comments: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          comment: "Left Distal Thigh Diagnosis",
        },
      ],
      biopsy_findings: {
        number_of_fibers: 2,
        nerve_fiber_density: "Consistent with...",
        neuropathy_type: "Length-dependent neuropathy",
      },
      notes: [
        {
          text: "The biopsies demonstrate...",
        },
        {
          text: "The biopsies demonstrate...",
        },
      ],
    },
  },
  {
    report_no: "2411",
    status: "Final",
    ordering_provider: "California State Hospital",
    ordering_physician: "Dr. Zimmerna",
    facility: "Downtown Clinic",
    cpts: ["41612", "88005"],
    icds: ["G60.3", "G455.2"],
    apply_date: "2025-01-02T17:30:00",
    report_date: "2025-01-02T17:30:00",
    patient: {
      id: 20,
      first_name: "Sofia",
      last_name: "King",
      email: "sofia.king@example.com",
      phone: "(555) 654-9876",
      address: "321 Elm St",
      apt_number: "56789",
      gender: "Female",
      date_of_birth: "1990-09-30",
      insurance_company: "Humana",
      member_id: "HU123443322",
      reasons: ["Joint pain", "Swelling"],
      sensory_symptoms: ["No sensory symptoms"],
      ethnicity: "African American",
      ordering_physician: "Dr. Jenkins",
    },
    disorder_observation: {
      metabolic: [
        {
          code: "E03.9",
          description: "Hypothyroidism, unspecified",
        },
        {
          code: "E10.40",
          description: "Type 1 DM with diabetic neuropathy, unspecified",
        },
      ],
    },
    reason_for_skin_biopsy: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    communication_with_patient: [
      "To diagnose or monitor medical conditions or to plan treatment based on pathology supported information",
      "To provide documentation, for purposes of insurance coverage, to support recommended treatments.",
    ],
    clinical_symptoms: {
      neck_pain: [
        {
          description: "Spinal stenosis, cervical region",
          code: "M48.02",
          side: "Left",
        },
        {
          description: "Cervicalgia",
          code: "M54.2",
          side: "Right",
        },
      ],
      leg_pain: [
        {
          description: "Coldness in your neck",
          side: "Both",
        },
        {
          description: "Discomfort in your neck wakes you up at night",
          side: "Right",
        },
      ],
    },
    biopsy_samples: [
      {
        location: "Proximal Arm",
        abbreviation: "PA",
        side: "Left",
        specimen_id: "61961465165",
      },
      {
        location: "Proximal Thigh",
        abbreviation: "PT",
        side: "Left",
        specimen_id: "61961465166",
      },
      {
        location: "Calf",
        abbreviation: "C",
        side: "Left",
        specimen_id: "61961465167",
      },
      {
        location: "Ankle",
        abbreviation: "A",
        side: "Left",
        specimen_id: "61961465168",
      },
    ],
    documents: ["MPS-SOAP NOTE", "MPS-Test Testing-REO-H4NPX"],
    pathologist_section: {
      final_microscopic_diagnosis: {
        normal: ">9",
        borderline: "7.2-8.9",
        mild: "3.9-7.1",
        moderate: "2.1-3.8",
        severe: "0-2",
      },
      samples: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
          canned_dx: "There is no pathologic abnormality seen.",
        },
      ],
      microscopic_examination: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      gross_description: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          diagnosis: "Left Distal Thigh Diagnosis",
        },
      ],
      comments: [
        {
          location: "Proximal Arm",
          abbreviation: "PA",
          side: "Left",
          specimen_id: "61961465165",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Proximal Thigh",
          abbreviation: "PT",
          side: "Left",
          specimen_id: "61961465166",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Calf",
          abbreviation: "C",
          side: "Left",
          specimen_id: "61961465167",
          comment: "Left Distal Thigh Diagnosis",
        },
        {
          location: "Ankle",
          abbreviation: "A",
          side: "Left",
          specimen_id: "61961465168",
          comment: "Left Distal Thigh Diagnosis",
        },
      ],
      biopsy_findings: {
        number_of_fibers: 2,
        nerve_fiber_density: "Consistent with...",
        neuropathy_type: "Length-dependent neuropathy",
      },
      notes: [
        {
          text: "The biopsies demonstrate...",
        },
        {
          text: "The biopsies demonstrate...",
        },
      ],
    },
  },
];
