export const usersData = [
  {
    id: 1001,
    first_name: "John",
    last_name: "Doe",
    email: "johndoe@email.com",
    phone: "+1-202-555-0173",
    address: "123 Main St, Springfield, IL",
    company: "Springfield Medical Center",
    role: "doctor",
    status: "active",
    npi: "1234567890",
    apt_number: "48293",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1002,
    first_name: "Sarah",
    last_name: "Miller",
    email: "sarah.miller@email.com",
    phone: "+1-303-555-0194",
    address: "450 Sunset Blvd, Denver, CO",
    company: "Rocky Mountain Pathology",
    role: "pathologist",
    status: "blocked",
    facility_location: "Rocky Mountain Diagnostic Lab",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1003,
    first_name: "Michael",
    last_name: "Brown",
    email: "michael.brown@email.com",
    phone: "+1-415-555-0127",
    address: "789 Oak St, San Francisco, CA",
    company: "Bay Area Medical",
    role: "doctor",
    status: "active",
    npi: "9876543210",
    apt_number: "25931",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1004,
    first_name: "Emma",
    last_name: "Davis",
    email: "emma.davis@email.com",
    phone: "+1-646-555-0182",
    address: "55 Lexington Ave, New York, NY",
    company: "NYC Histology Lab",
    role: "histologist",
    status: "active",
    facility_location: "NYC Pathology Research Center",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1005,
    first_name: "James",
    last_name: "Wilson",
    email: "james.wilson@email.com",
    phone: "+1-305-555-0176",
    address: "210 Ocean Dr, Miami, FL",
    company: "Florida 100Medical Group",
    role: "doctor",
    status: "blocked",
    npi: "5678901234",
    apt_number: "37482",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1006,
    first_name: "Alice",
    last_name: "Johnson",
    email: "alice.johnson@email.com",
    phone: "+1-617-555-0168",
    address: "999 Commonwealth Ave, Boston, MA",
    company: "Boston Medical Center",
    role: "admin",
    status: "active",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1007,
    first_name: "Ethan",
    last_name: "Martinez",
    email: "ethan.martinez@email.com",
    phone: "+1-312-555-0185",
    address: "77 Lakeshore Dr, Chicago, IL",
    company: "Midwe100st Medical Diagnostics",
    role: "representative",
    status: "blocked",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1008,
    first_name: "Rachel",
    last_name: "Lopez",
    email: "rachel.lopez@email.com",
    phone: "+1-213-555-0171",
    address: "500 Sunset Blvd, Los Angeles, CA",
    company: "California Medical Systems",
    role: "admin",
    status: "active",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1009,
    first_name: "Daniel",
    last_name: "Harris",
    email: "daniel.harris@email.com",
    phone: "+1-919-555-0193",
    address: "102 Greenway Blvd, Raleigh, NC",
    company: "Carolina Healthcare",
    role: "admin",
    status: "active",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1010,
    first_name: "Olivia",
    last_name: "Clark",
    email: "olivia.clark@email.com",
    phone: "+1-513-555-0189",
    address: "88 River Rd, Cincinnati, OH",
    company: "Ohio Diagnostic Lab",
    role: "representative",
    status: "active",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1011,
    first_name: "David",
    last_name: "Walker",
    email: "david.walker@email.com",
    phone: "+1-702-555-0155",
    address: "390 Desert Rd, Las Vegas, NV",
    company: "Nevada Health Group",
    role: "doctor",
    status: "active",
    npi: "3456789012",
    apt_number: "12345",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1012,
    first_name: "Sophia",
    last_name: "Hall",
    email: "sophia.hall@email.com",
    phone: "+1-503-555-0199",
    address: "1200 Rosewood St, Portland, OR",
    company: "Oregon Pathology Lab",
    role: "pathologist",
    status: "active",
    facility_location: "Oregon Medical Diagnostics",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1013,
    first_name: "Ryan",
    last_name: "Scott",
    email: "ryan.scott@email.com",
    phone: "+1-212-555-0178",
    address: "405 Park Ave, New York, NY",
    company: "NYC Medical Center",
    role: "admin",
    status: "active",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1014,
    first_name: "Natalie",
    last_name: "Robinson",
    email: "natalie.robinson@email.com",
    phone: "+1-214-555-0183",
    address: "600 Elm St, Dallas, TX",
    company: "Texas Medical Group",
    role: "representative",
    status: "active",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1015,
    first_name: "Justin",
    last_name: "King",
    email: "justin.king@email.com",
    phone: "+1-415-555-0172",
    address: "950 Bay St, San Francisco, CA",
    company: "California Health Services",
    role: "doctor",
    status: "active",
    npi: "6789012345",
    apt_number: "67890",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1016,
    first_name: "Emily",
    last_name: "Carter",
    email: "emily.carter@email.com",
    phone: "+1-718-555-0123",
    address: "111 Broadway, Brooklyn, NY",
    company: "New York Histology Lab",
    role: "histologist",
    status: "active",
    facility_location: "NYC Clinical Research",
    image: "https://randomuser.me/api/portraits/women/16.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1017,
    first_name: "Brandon",
    last_name: "Lewis",
    email: "brandon.lewis@email.com",
    phone: "+1-919-555-0190",
    address: "50 Pine St, Raleigh, NC",
    company: "Carolina Health Group",
    role: "admin",
    status: "active",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1018,
    first_name: "Hannah",
    last_name: "Martinez",
    email: "hannah.martinez@email.com",
    phone: "+1-407-555-0177",
    address: "777 Orlando Dr, Orlando, FL",
    company: "Florida Health Systems",
    role: "representative",
    status: "active",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1019,
    first_name: "Tyler",
    last_name: "Harris",
    email: "tyler.harris@email.com",
    phone: "+1-205-555-0165",
    address: "222 Oak St, Birmingham, AL",
    company: "Alabama Health Services",
    role: "doctor",
    status: "active",
    npi: "8901234567",
    apt_number: "23456",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1020,
    first_name: "Lauren",
    last_name: "Mitchell",
    email: "lauren.mitchell@email.com",
    phone: "+1-605-555-0152",
    address: "333 Dakota St, Sioux Falls, SD",
    company: "Midwest Medical",
    role: "histologist",
    status: "active",
    facility_location: "South Dakota Diagnostic Center",
    image: "https://randomuser.me/api/portraits/women/20.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1021,
    first_name: "Gregory",
    last_name: "Adams",
    email: "gregory.adams@email.com",
    phone: "+1-818-555-0144",
    address: "750 Hollywood Blvd, Los Angeles, CA",
    company: "California Diagnostics",
    role: "admin",
    status: "active",
    image: "https://randomuser.me/api/portraits/men/21.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
  {
    id: 1022,
    first_name: "Isabella",
    last_name: "Parker",
    email: "isabella.parker@email.com",
    phone: "+1-225-555-0133",
    address: "45 Bayou St, Baton Rouge, LA",
    company: "Louisiana Medical Group",
    role: "representative",
    status: "active",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
    signature:
      "https://st.1001fonts.net/img/illustrations/s/i/signaturex-demo-font-2-large.png",
  },
];
